### ISSUE TITLE
Implement chart

### ISSUE THREAD

**Issue by jenni** [jen-v/whoishiring#1]
Using `react-chartjs` for example.

**Comment by nickisaacs** [comment]
Hi, I could pick this up. Can you please provide details

**Comment by jenni** [comment]
Hi @nickisaacs, awesome! :) This small project is a visual representation of the companies that post open positions in Berlin.

This is a sample of how it used to look: http://startups-chart.bitballoon.com/ , it's broken and incomplete since a very long time ago, and I decided to re-do the project recently. 

The idea is to implement a line chart with the days of the month in the Y axis, ideally it would cover the whole year and horizontal scrolling, but one chart per month is also nice.

There's only one endpoint that provides a collection of companies, each company has an array with the data collected every day, in the following example there's one company with data that corresponds to just two consecutive days:

```
[  
  {  
    "_id":"5b265b895df7030004694bdc",
    "name":"Axel Springer SE",
    "data":[  
      {  
        "date":"2018-06-18T13:00:55.945Z",
        "_id":"5b265b895df7030004694bdd",
        "value":3
      },
      {  
        "date":"2018-06-19T13:01:10.216Z",
        "_id":"5b28fe978b7e3a00045d94f8",
        "value":3
      }
    ],
    "__v":0
  },
  ...
]
```

**Comment by nickisaacs** [comment]
@jen-v 
Cool!

- Do you want me to build a UI-layer on this same repo? Or do you want it to be a separate project?
- How many companies do you want displayed on the chart? The current application shows the Top 7. How should I calculate the top 7?

**Comment by jenni** [comment]
@nickisaacs I think building the UI on this repo makes sense :)
About the displayed companies, this should be an average of the values in the data array per company, and take the ones with highest average.

**Comment by nickisaacs** [comment]
@jen-v 
Okay!

**Comment by nickisaacs** [comment]
@jen-v 
I've implemented a basic line chart. Could you please update the API to return only the required data, as I think this should not be done at the UI. Right now, I'm getting an array of 500+ companies

**Comment by jenni** [comment]
@nickisaacs, can't wait to see it! :) I've added a quick `splice` to serve only 10 companies, that should do the job for now.

**Comment by nickisaacs** [comment]
@jen-v 
Its still WIP, but it is a step forward :)
https://github.com/jen-v/whoishiring/pull/2

**Comment by jenni** [comment]
I'm closing here as the PR is merged. Feel free to add more issues for the missing stuff / if you're going to work on something else. Thanks a lot again!
